services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:amd64-4.0.16
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./sonarr/data:/config
      - ./tv:/tv 
      - ./downloads:/downloads 
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./radarr/data:/config
      - ./movies:/movies 
      - ./downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.4
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent/data:/config
      - ./downloads:/downloads 
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.6
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./bazarr/data:/config
      - ./movies:/movies 
      - ./tv:/tv 
    ports:
      - 6767:6767
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.6
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./jellyfin/data:/config
      - ./tv:/data/tvshows
      - ./movies:/data/movies
      - ./jellyseerr/jelly-bridge:/data/JellyBridge
    ports:
      - 8096:8096
      - 8920:8920 
      - 7359:7359/udp 
      - 1900:1900/udp 
    restart: unless-stopped

  jellyseerr:
      image: fallenbagel/jellyseerr:2.7.3
      container_name: jellyseerr
      environment:
          - LOG_LEVEL=debug
          - TZ=Asia/Tashkent
      ports:
          - 5055:5055
      volumes:
          - ./jellyseerr/data:/app/config
          - ./jellyseerr/jelly-bridge:/data/JellyBridge
