apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack-default
    receivers:
      - uid: slack-default
        type: slack
        settings:
          url: ${GRAFANA_SLACK_WEBHOOK_URL}
          recipient: "#homelab"
          title: '{{ template "default.title" . }}'
          text: '{{ template "default.message" . }}'
