apiVersion: 1

policies:
  - orgId: 1
    receiver: slack-default
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: slack-default
        object_matchers:
          - ["severity", "=", "critical"]
      - receiver: slack-default
        object_matchers:
          - ["severity", "=", "warning"]
